#!/bin/bash
#
# Photography Image Processor
# ============================
# Converts, resizes, and generates thumbnails for the photography page.
# Also generates the _data/photos.yml file from the processed images.
#
# USAGE:
#   ./scripts/process-photos.sh <input_directory>
#
# INPUT FORMAT:
#   Place images in the input directory with filenames in the format:
#     category - description.ext
#   Examples:
#     mountains - Moraine Lake Banff.heic
#     europe - Venice Bridge.jpg
#     cities - Calgary Tower Snow.png
#     coasts - Caribbean Beach.HEIC
#     nature - Red Panda.jpeg
#
#   Supported input formats: HEIC, JPG, JPEG, PNG, WEBP
#   Spaces in names are fine. Category and description are separated by " - "
#
# OUTPUT:
#   - assets/img/photography/converted/  (full-size JPEGs, max 1600px, 80% quality)
#   - assets/img/photography/thumbs/     (thumbnails, max 400px)
#   - _data/photos.yml                   (photo metadata for Jekyll)
#
# REQUIREMENTS:
#   - macOS with `sips` (built-in) — no extra dependencies needed
#
# CATEGORY SUGGESTIONS:
#   mountains, europe, cities, coasts, nature
#   (You can add any category — the photography page groups by category)

set -euo pipefail

# --- Configuration ---
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CONVERTED_DIR="$PROJECT_ROOT/assets/img/photography/converted"
THUMBS_DIR="$PROJECT_ROOT/assets/img/photography/thumbs"
DATA_FILE="$PROJECT_ROOT/_data/photos.yml"
MAX_FULL_SIZE=1600
MAX_THUMB_SIZE=400
JPEG_QUALITY=80

# --- Category display names and order ---
CATEGORY_ORDER="mountains europe cities coasts nature"

get_category_title() {
  case "$1" in
    mountains) echo "🏔️ Mountains & Lakes" ;;
    europe)    echo "🏰 European Adventures" ;;
    cities)    echo "🌃 Cities & Nightlife" ;;
    coasts)    echo "🌅 Coasts & Sunsets" ;;
    nature)    echo "🌿 Nature & Gardens" ;;
    *)         echo "$1" ;;
  esac
}

# --- Functions ---
usage() {
  echo "Usage: $0 <input_directory>"
  echo ""
  echo "Input files should be named: category - description.ext"
  echo "Example: mountains - Moraine Lake Banff.heic"
  echo ""
  echo "Run from the project root or any directory."
  exit 1
}

slugify() {
  # Convert description to a URL-safe filename
  echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//'
}

process_image() {
  local input_file="$1"
  local filename
  filename="$(basename "$input_file")"

  # Extract extension (case-insensitive)
  local ext="${filename##*.}"
  ext="$(echo "$ext" | tr '[:upper:]' '[:lower:]')"

  # Remove extension to get "category - description"
  local name_part="${filename%.*}"

  # Parse category and description
  if [[ "$name_part" != *" - "* ]]; then
    echo "  SKIP: '$filename' — missing ' - ' separator (expected: category - description.ext)"
    return 1
  fi

  local category="${name_part%% - *}"
  local description="${name_part#* - }"
  category="$(echo "$category" | tr '[:upper:]' '[:lower:]' | xargs)"
  description="$(echo "$description" | xargs)"

  # Generate output filename
  local slug
  slug="$(slugify "$description")"
  local output_name="${category}-${slug}.jpg"

  echo "  Processing: $filename → $output_name (category: $category)"

  # Convert to JPEG and resize (full-size)
  sips -s format jpeg -s formatOptions "$JPEG_QUALITY" \
    --resampleHeightWidthMax "$MAX_FULL_SIZE" \
    "$input_file" --out "$CONVERTED_DIR/$output_name" >/dev/null 2>&1

  # Generate thumbnail
  sips -s format jpeg -s formatOptions "$JPEG_QUALITY" \
    --resampleHeightWidthMax "$MAX_THUMB_SIZE" \
    "$input_file" --out "$THUMBS_DIR/$output_name" >/dev/null 2>&1

  # Store for YAML generation (using a temp file for cross-function data)
  echo "${category}|${description}|${output_name}" >> "$TEMP_MANIFEST"
}

generate_yaml() {
  echo "Generating $DATA_FILE..."

  # Sort manifest by category order, then alphabetically within category
  echo "# Auto-generated by scripts/process-photos.sh" > "$DATA_FILE"
  echo "# Re-run the script to regenerate after adding/removing photos." >> "$DATA_FILE"
  echo "#" >> "$DATA_FILE"
  echo "# categories: list of category groups with title, id, and photos" >> "$DATA_FILE"
  echo "" >> "$DATA_FILE"
  echo "categories:" >> "$DATA_FILE"

  # Collect all unique categories from the manifest
  local all_categories
  all_categories=$(cut -d'|' -f1 "$TEMP_MANIFEST" | sort -u)

  # Process known categories first (in order), then any unknown ones
  local processed=""
  for cat in $CATEGORY_ORDER; do
    if grep -q "^${cat}|" "$TEMP_MANIFEST" 2>/dev/null; then
      write_category_yaml "$cat"
      processed="$processed $cat"
    fi
  done

  # Handle any categories not in the predefined order
  for cat in $all_categories; do
    case " $processed " in
      *" $cat "*) ;;
      *) write_category_yaml "$cat" ;;
    esac
  done
}

write_category_yaml() {
  local cat="$1"
  local title
  title="$(get_category_title "$cat")"

  echo "  - id: $cat" >> "$DATA_FILE"
  echo "    title: \"$title\"" >> "$DATA_FILE"
  echo "    photos:" >> "$DATA_FILE"

  grep "^${cat}|" "$TEMP_MANIFEST" | sort -t'|' -k2 | while IFS='|' read -r _cat desc file; do
    echo "      - file: \"$file\"" >> "$DATA_FILE"
    echo "        caption: \"$desc\"" >> "$DATA_FILE"
  done

  echo "" >> "$DATA_FILE"
}

# --- Main ---
if [[ $# -lt 1 ]]; then
  usage
fi

INPUT_DIR="$1"

if [[ ! -d "$INPUT_DIR" ]]; then
  echo "Error: '$INPUT_DIR' is not a directory."
  exit 1
fi

# Create output directories
mkdir -p "$CONVERTED_DIR" "$THUMBS_DIR"

# Temp file for collecting processed image info
TEMP_MANIFEST="$(mktemp)"
trap 'rm -f "$TEMP_MANIFEST"' EXIT

echo "=== Photography Image Processor ==="
echo "Input:     $INPUT_DIR"
echo "Converted: $CONVERTED_DIR"
echo "Thumbs:    $THUMBS_DIR"
echo "Data:      $DATA_FILE"
echo ""

# Count input files
file_count=0
skip_count=0
for f in "$INPUT_DIR"/*; do
  [[ -f "$f" ]] || continue
  ext="${f##*.}"
  ext="$(echo "$ext" | tr '[:upper:]' '[:lower:]')"
  case "$ext" in
    heic|jpg|jpeg|png|webp) ((file_count++)) ;;
  esac
done

echo "Found $file_count image(s) to process."
echo ""

# Process each image
for f in "$INPUT_DIR"/*; do
  [[ -f "$f" ]] || continue
  ext="${f##*.}"
  ext="$(echo "$ext" | tr '[:upper:]' '[:lower:]')"
  case "$ext" in
    heic|jpg|jpeg|png|webp)
      if ! process_image "$f"; then
        ((skip_count++))
      fi
      ;;
  esac
done

echo ""

if [[ ! -s "$TEMP_MANIFEST" ]]; then
  echo "No images were processed. Check the input file naming format."
  echo "Expected: category - description.ext"
  exit 1
fi

processed_count=$(wc -l < "$TEMP_MANIFEST" | tr -d ' ')
echo "Processed: $processed_count image(s), Skipped: $skip_count"
echo ""

# Generate YAML data file
generate_yaml

echo ""
echo "=== Done! ==="
echo "Full-size images: $CONVERTED_DIR/"
echo "Thumbnails:       $THUMBS_DIR/"
echo "Data file:        $DATA_FILE"
echo ""
echo "The photography page will automatically pick up changes from $DATA_FILE."
echo "Run 'bundle exec jekyll serve' to preview."
